- link:
    ~/Library/Application Support/Code/User/settings.json:
      force: true
      path: vscode/settings.json

- shell:
  - [./vscode/install-extensions.sh, Installing vscode extensions]      