- defaults:
    link:
      force: true
      create: true
      relink: true
    shell:
      quiet:  false
      stdout: true
      stdin:  true
      stderr: true

- clean: ['~']

- link:
    ~/.dotfiles: ''

- shell:
  - [sudo -v, Ask for sudo password in advance]
  - ["git submodule update --init --recursive", "Installing submodules"]