
- defaults:
    link:
      force: true
      create: true
      relink: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]
    - [./homebrew/brew.sh, Installing homebrew binaries and apps]
    - [./vscode/install-extensions.sh, Installing vscode extensions]

- clean: ['~']    