
- defaults:
    link:
      force: true
      create: true
      relink: true
    shell:
      quiet:  false
      stdout: true
      stdin:  true
      stderr: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]

- clean: ['~']    