---
- name: Check which LaunchAgents are loaded
  shell: "launchctl list"
  register: loaded_agents

- name: Load custom LaunchAgents if not loaded
  shell: "launchctl load ~/Library/LaunchAgents/{{ item }}.plist"
  when: loaded_agents is not search(item)
  with_items: "{{ launch_agents_load }}"
