---
dotfiles_destination_directory: "~/.dotfiles"

shared_symlinks:
  - { src: "zshrc", dest: "~/.zshrc" }
  - { src: "git/gitconfig", dest: "~/.gitconfig" }
  - { src: "editorconfig", dest: "~/.editorconfig" }
  - { src: "karabiner/karabiner.edn", dest: "~/.config/karabiner.edn" }
  - { src: "iterm/com.googlecode.iterm2.plist", dest: "~/Library/Preferences/com.googlecode.iterm2.plist" }
  - { src: "launchd/com.mateusrevoredo.alfred-gdrive.plist", dest: "~/Library/LaunchAgents/com.mateusrevoredo.alfred-gdrive.plist" }

shared_vscode_extensions:
  - CoenraadS.bracket-pair-colorizer-2
  - EditorConfig.EditorConfig
  - Equinusocio.vsc-material-theme
  - formulahendry.auto-close-tag
  - HookyQR.beautify
  - k--kato.intellij-idea-keybindings
  - Lencerf.beancount
  - ms-azuretools.vscode-docker
  - ms-mssql.mssql
  - ms-python.python
  - msjsdiag.debugger-for-chrome
  - vscode-icons-team.vscode-icons
  - vscoss.vscode-ansible

asdf_version: "v0.7.8"
asdf_init_shell: false
asdf_plugins:
  - name: "python"
    versions:
      - "3.6.10"
    global: "3.6.10"
  - name: "nodejs"
    versions:
      - "12.18.0"
    global: "12.18.0"
  - name: "php"
    versions:
      - "7.4.5"
    global: "7.4.5"
