---
dotfiles_destination_directory: "~/.dotfiles"

shared_symlinks:
  - { src: "zshrc", dest: "~/.zshrc" }
  - { src: "git/gitconfig", dest: "~/.gitconfig" }
  - { src: "editorconfig", dest: "~/.editorconfig" }
  - { src: "asdf/default-npm-packages", dest: "~/.default-npm-packages" }
  - { src: "asdf/default-python-packages", dest: "~/.default-python-packages" }

shared_vscode_extensions:
  - 2gua.rainbow-brackets
  - CoenraadS.bracket-pair-colorizer-2
  - dongfg.vscode-beancount-formatter
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - formulahendry.auto-close-tag
  - HookyQR.beautify
  - k--kato.intellij-idea-keybindings
  - Lencerf.beancount
  - lextudio.restructuredtext
  - ms-azuretools.vscode-docker
  - ms-mssql.mssql
  - ms-python.python
  - msjsdiag.debugger-for-chrome
  - oderwat.indent-rainbow
  - redhat.vscode-yaml
  - redhat.vscode-xml
  - shardulm94.trailing-spaces
  - streetsidesoftware.code-spell-checker
  - tyriar.sort-lines
  - vscode-icons-team.vscode-icons
  - vscoss.vscode-ansible
  - wholroyd.jinja

asdf_home: "{{ ansible_env.HOME }}"
asdf_dir: "{{ asdf_home }}/.asdf"
asdf_version: "v0.7.8"
asdf_init_shell: false
asdf_plugins:
  - name: "python"
    versions:
      - "3.6.10"
    global: "3.6.10"
  - name: "nodejs"
    versions:
      - "12.18.0"
    global: "12.18.0"
  - name: "php"
    versions:
      - "7.4.5"
    global: "7.4.5"
